CREATE TABLE IF NOT EXISTS ADDRESS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    street VARCHAR(255),
    city VARCHAR(255),
    zipCode VARCHAR(10),
    country VARCHAR(255)
);
CREATE SEQUENCE IF NOT EXISTS ADDRESS_SEQ;

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    address_id BIGINT,
    FOREIGN KEY (address_id) REFERENCES ADDRESS(id)
);
CREATE SEQUENCE IF NOT EXISTS USERS_SEQ;